{{ if  or (.Capabilities.APIVersions.Has "ricoberger.de/v1alpha1/VaultSecret") (.Values.global.useVaultSecrets) -}}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Release.Name }}-workflow
spec:
  keys:
    - NPM_TOKEN
    - GITHUB_TOKEN
    - dockerconfigjson
  path: pipelines/workflows
  templates:
    NPM_TOKEN: "{% .Secrets.NPM_TOKEN %}"
    GITHUB_TOKEN: "{% .Secrets.GITHUB_TOKEN %}"
    .dockerconfigjson: "{\"auths\": {\"ghcr.io\": {\"auth\": \"{% .Secrets.dockerconfigjson | b64enc %}\"}}}"
  type: Opaque
{{ else -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-workflow
type: Opaque
data:
  NPM_TOKEN: "{{ .Values.env.NPM_TOKEN | b64enc}}"
  GITHUB_TOKEN: "{{ .Values.env.GITHUB_TOKEN | b64enc}}"
  .dockerconfigjson: {{ template "imagePullSecret" $ }}
{{ end -}}

