{{- if or .Values.minio.persistence.enabled .Values.postgresql.primary.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipelines-engine-storage
  labels:
    app: {{ .Release.Name }}-storage
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: {{ .Release.Name }}-storage
{{- end }}