{{ if  or (.Capabilities.APIVersions.Has "ricoberger.de/v1alpha1/VaultSecret") (.Values.global.useVaultSecrets) -}}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: argocd-vault-plugin-credentials
spec:
  keys:
    - VAULT_ADDR
    - VAULT_TOKEN
    - AVP_TYPE
    - AVP_AUTH_TYPE
  path: delivery-engine/argocd
  templates:
    VAULT_ADDR: "{% .Secrets.VAULT_ADDR %}"
    VAULT_TOKEN: "{% .Secrets.VAULT_TOKEN %}"
    AVP_TYPE: "{% .Secrets.AVP_TYPE  %}"
    AVP_AUTH_TYPE: "{% .Secrets.AVP_AUTH_TYPE  %}"
  type: Opaque
{{ end -}}

