{{ if  or (.Capabilities.APIVersions.Has "ricoberger.de/v1alpha1/VaultSecret") (.Values.global.useVaultSecrets) -}}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: dex-oidc-auth0
  labels: 
    app.kubernetes.io/part-of: argocd
spec:
  keys:
    - AUTH0_CLIENT_ID
    - AUTH0_CLIENT_SECRET
  path: pipelines/workflows
  templates:
    AUTH0_CLIENT_ID: "{% .Secrets.AUTH0_CLIENT_ID %}"
    AUTH0_CLIENT_SECRET: "{% .Secrets.AUTH0_CLIENT_SECRET %}"
  type: Opaque
{{ else -}}
apiVersion: v1
kind: Secret
metadata:
  name: dex-oidc-auth0
  labels: 
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  AUTH0_CLIENT_ID: "{{ .Values.env.AUTH0_CLIENT_ID | b64enc}}"
  AUTH0_CLIENT_SECRET: "{{ .Values.env.AUTH0_CLIENT_SECRET | b64enc}}"
{{ end -}}
