{
 "title": "Apollo GraphQL Metrics",
 "description": "Apollo GraphQL metrics. Mutations/errors/operations.",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(apollo_query_resolved, namespace)"
    }
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "label_values(apollo_query_resolved, operation)"
    }
   },
   {
    "name": "operation_name",
    "label": "Operation Name",
    "query": {
     "query": "label_values(apollo_query_resolved, operation_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(apollo_query_resolved{namespace=~\"$namespace\"}[$__range])) by (namespace)"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(increase(apollo_query_failed{namespace=~\"$namespace\"}[$__range]) OR vector(0)) by (namespace) / sum(increase(apollo_query_resolved{namespace=~\"$namespace\"}[$__range])) by (namespace))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(apollo_query_failed{namespace=~\"$namespace\"}[$__range])) by (namespace)"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(apollo_query_failed{namespace=~\"$namespace\", operation=\"query\"}[$__range])) by (namespace)"
    }
   ]
  },
  {
   "title": "Mutation Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(apollo_query_failed{namespace=~\"$namespace\", operation=\"mutation\"}[$__range])) by (namespace)"
    }
   ]
  },
  { "title": "Individual Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(apollo_query_failed{namespace=~\"$namespace\", operation=~\"$operation\"}[$__range])) by (operation, operation_name, namespace) > 0"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(apollo_query_resolved{namespace=~\"$namespace\", operation=~\"$operation\"}[$__range])) by (operation, operation_name, namespace) > 0"
    }
   ]
  }
 ]
}