{{- if or .Values.grafana.persistence.enabled .Values.loki.persistence.enabled .Values.prometheus.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-storage
  labels:
    app: {{ .Release.Name }}-storage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: {{ .Release.Name }}-storage
    fsType: ext4
{{- end }}