apiVersion: v1
kind: Secret
metadata:
  name: argo-postgres-config
  namespace: {{ .Release.namespace }}
type: Opaque
data:
  {{- if and .Values.postgresql.auth.username .Values.postgresql.auth.password  }}
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}
  {{- else }}
    {{- if .Values.postgresql.auth.postgresPassword  }}
  username: {{ "postgres" | b64enc }}
  password: {{ .Values.postgresql.auth.postgresPassword | b64enc }}
    {{- end }}
  {{- end }}