{{ if  or (.Capabilities.APIVersions.Has "ricoberger.de/v1alpha1/VaultSecret") (.Values.global.useVaultSecrets) -}}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pipelines-engine-default-regcred
spec:
  keys:
    - NPM_TOKEN
    - GITHUB_TOKEN
    - dockerconfigjson
  path: pipelines-engine/workflows
  templates:
    .dockerconfigjson: "{\"auths\": {\"ghcr.io\": {\"auth\": \"{% .Secrets.dockerconfigjson | b64enc %}\"}}}"
  type: kubernetes.io/dockerconfigjson
{{ else -}}
apiVersion: v1
kind: Secret
metadata:
  name: pipelines-engine-default-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" $ }}
{{ end -}}

