global:
  useVaultSecrets: false

image: 
  repository: ghcr.io/web-seven/composition-engine
  tag:

env:
  GITHUB_TOKEN: ""
  GITHUB_USER: ""
  NPM_TOKEN: ""

workflow:
  nodeSelector:

eventBusName: "pipelines-eventbus"

build:
  chartRegistry: web-seven/infrastructure
  imageRegistry: ghcr.io/web-seven
  monoRepo:
    enabled: true
    type: "nx"
    repository:
      server: github.com
      owner: web-seven
      name: web-seven

ingress:
  enabled: true
  host: pipelines.local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/mergeable-ingress-type: "minion"

webhook:
  enabled: true
  service:
    port: 12000
  path: "/webhook/{{ .Release.Name }}"

github:
  enabled: true
  refPattern: '^refs\/heads\/(develop|stage|production|main|master)$'
  service:
    ports:
    - port: "12000"
      targetPort: "12000"
  appRepo:
    repositories:
    - owner: web-seven
      names:
      - web-seven
    webhook:
      endpoint: "/github/{{ .Release.Name }}"
      port: 12000
      method: "POST"
